"""
Pydantic Schemas Package for QUANTLAB API.
"""
from backend.app.schemas.market import (
    MarketDataPoint,
    AssetItem,
    AssetListResponse,
    AssetMetadataResponse,
    DateRangeInfo,
    MultiAssetDateRangeResponse,
    HistoricalDataResponse,
    MultiAssetHistoricalDataResponse,
    ErrorResponse,
)
from backend.app.schemas.quant import (
    IndicatorDataPoint,
    IndicatorResponse,
    ReturnDataPoint,
    ReturnsResponse,
    VolatilityDataPoint,
    VolatilityResponse,
    RiskMetricsResponse,
    RollingPerformancePoint,
    RollingPerformanceResponse,
    DailyReturnStats,
    AssetQuantSummaryResponse,
)
from backend.app.schemas.correlation import (
    PairCorrelationResponse,
    CorrelationMatrixResponse,
    RollingCorrelationPoint,
    RollingCorrelationResponse,
    AssetComparisonMetrics,
    AssetComparisonResponse,
)
from backend.app.schemas.strategy import (
    StrategySignalPoint,
    SignalCounts,
    StrategyResponse,
)
from backend.app.schemas.backtesting import (
    BacktestRequest,
    BacktestMeta,
    StrategyMeta,
    BacktestPerformance,
    BenchmarkPerformance,
    BacktestComparison,
    EquityCurvePoint,
    TradeRecord,
    OpenPosition,
    BacktestResponse,
    StrategyInfo,
    StrategyInfoListResponse,
)

__all__ = [
    "MarketDataPoint",
    "AssetItem",
    "AssetListResponse",
    "AssetMetadataResponse",
    "DateRangeInfo",
    "MultiAssetDateRangeResponse",
    "HistoricalDataResponse",
    "MultiAssetHistoricalDataResponse",
    "ErrorResponse",
    "IndicatorDataPoint",
    "IndicatorResponse",
    "ReturnDataPoint",
    "ReturnsResponse",
    "VolatilityDataPoint",
    "VolatilityResponse",
    "RiskMetricsResponse",
    "RollingPerformancePoint",
    "RollingPerformanceResponse",
    "DailyReturnStats",
    "AssetQuantSummaryResponse",
    "PairCorrelationResponse",
    "CorrelationMatrixResponse",
    "RollingCorrelationPoint",
    "RollingCorrelationResponse",
    "AssetComparisonMetrics",
    "AssetComparisonResponse",
    "StrategySignalPoint",
    "SignalCounts",
    "StrategyResponse",
    "BacktestRequest",
    "BacktestMeta",
    "StrategyMeta",
    "BacktestPerformance",
    "BenchmarkPerformance",
    "BacktestComparison",
    "EquityCurvePoint",
    "TradeRecord",
    "OpenPosition",
    "BacktestResponse",
    "StrategyInfo",
    "StrategyInfoListResponse",
]


