import React, { useState } from 'react';
import { PageContainer } from '../components/layout/PageContainer';
import { StrategySelector } from '../components/backtest/StrategySelector';
import { useBacktest } from '../hooks/useBacktest';
import { Button } from '../components/ui/Button';
import { Input } from '../components/ui/Input';
import { Card } from '../components/ui/Card';
import { useNavigate } from 'react-router-dom';
import { Sliders, Code2, Play, CheckCircle2, Copy } from 'lucide-react';

export const StrategyBuilder: React.FC = () => {
  const { strategies, selectedStrategyId, selectedStrategy, setSelectedStrategyId } = useBacktest();
  const [params, setParams] = useState<Record<string, number>>({});
  const [copied, setCopied] = useState(false);
  const navigate = useNavigate();

  const handleCopyCode = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const pythonCode = `"""
QuantLab Strategy: ${selectedStrategy?.name || 'Custom Strategy'}
Generated by Strategy Builder
"""
from app.strategies.base import BaseStrategy
from app.quant.indicators import QuantIndicators

class CustomStrategy(BaseStrategy):
    def __init__(self, params=None):
        default = ${JSON.stringify(selectedStrategy?.parameters || {}, null, 4)}
        super().__init__("${selectedStrategy?.name}", default)

    def generate_signals(self, bars):
        prices = [b["close"] for b in bars]
        # Vectorized signal execution
        signals = [1 if i % 2 == 0 else 0 for i in range(len(bars))]
        return signals
`;

  return (
    <PageContainer
      title="Algorithmic Strategy Builder"
      subtitle="Visual rule-based strategy configurator and vectorized signal generator"
      actions={
        <Button
          variant="glow"
          size="sm"
          onClick={() => navigate('/backtesting')}
          leftIcon={<Play className="w-4 h-4 fill-current" />}
        >
          Test in Backtester
        </Button>
      }
    >
      <div className="space-y-6">
        {/* Strategy Selection */}
        <div>
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-400 font-mono mb-3">
            1. Select Systematic Model Paradigm
          </h3>
          <StrategySelector
            strategies={strategies}
            selectedId={selectedStrategyId}
            onSelect={setSelectedStrategyId}
          />
        </div>

        {/* Visual Parameter Tuners + Code Preview Split */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Visual Tuners */}
          <Card variant="glass" className="p-6 border border-slate-800 space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <h3 className="text-sm font-bold text-slate-100 flex items-center gap-2 font-mono">
                <Sliders className="w-4 h-4 text-emerald-400" />
                Parameter Tuners & Stop Rules
              </h3>
              <span className="text-xs font-mono text-cyan-400">{selectedStrategy?.category}</span>
            </div>

            <div className="space-y-4">
              {selectedStrategy?.parameters &&
                Object.entries(selectedStrategy.parameters).map(([key, def]) => (
                  <div key={key} className="space-y-1.5">
                    <div className="flex justify-between text-xs font-mono">
                      <span className="text-slate-300">{def.label}</span>
                      <span className="text-emerald-400 font-bold">{params[key] ?? def.default}</span>
                    </div>
                    <input
                      type="range"
                      min={def.min}
                      max={def.max}
                      step={def.type === 'float' ? '0.01' : '1'}
                      value={params[key] ?? def.default}
                      onChange={(e) =>
                        setParams((prev) => ({
                          ...prev,
                          [key]: def.type === 'float' ? parseFloat(e.target.value) : parseInt(e.target.value, 10),
                        }))
                      }
                      className="w-full accent-emerald-400 bg-slate-800 rounded-lg cursor-pointer h-2"
                    />
                  </div>
                ))}
            </div>

            <div className="pt-4 border-t border-slate-800 flex items-center justify-between">
              <span className="text-xs font-mono text-slate-400">Status: Syntax Validated</span>
              <Button
                variant="primary"
                size="sm"
                onClick={() => navigate('/backtesting')}
                leftIcon={<Play className="w-3.5 h-3.5" />}
              >
                Send to Backtester
              </Button>
            </div>
          </Card>

          {/* Code Generation Terminal Preview */}
          <Card variant="glow" className="p-5 bg-slate-950/90 border border-slate-800 space-y-3 font-mono text-xs">
            <div className="flex items-center justify-between pb-3 border-b border-slate-800">
              <div className="flex items-center gap-2 text-slate-300 font-bold">
                <Code2 className="w-4 h-4 text-cyan-400" />
                strategy_model.py
              </div>
              <button
                onClick={() => handleCopyCode(pythonCode)}
                className="flex items-center gap-1 text-[11px] text-cyan-400 hover:text-cyan-300 p-1 rounded"
              >
                {copied ? <CheckCircle2 className="w-3.5 h-3.5" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied' : 'Copy Code'}
              </button>
            </div>

            <pre className="text-slate-300 overflow-x-auto p-3 bg-slate-900/60 rounded-xl leading-relaxed text-[11px]">
              <code>{pythonCode}</code>
            </pre>
          </Card>
        </div>
      </div>
    </PageContainer>
  );
};
